export const  ManyUser = [
    {
       "avatar":"https://reqres.in/img/faces/1-image.jpg",
       "email":"george.bluth@reqres.in",
       "first_name":"George",
       "id":11,
       "last_name":"Bluth"
    },
    {
       "avatar":"https://reqres.in/img/faces/2-image.jpg",
       "email":"janet.weaver@reqres.in",
       "first_name":"Janet",
       "id":12,
       "last_name":"Weaver"
    },
    {
       "avatar":"https://reqres.in/img/faces/3-image.jpg",
       "email":"emma.wong@reqres.in",
       "first_name":"Emma",
       "id":13,
       "last_name":"Wong"
    },
    {
       "avatar":"https://reqres.in/img/faces/4-image.jpg",
       "email":"eve.holt@reqres.in",
       "first_name":"Eve",
       "id":14,
       "last_name":"Holt"
    },
    {
       "avatar":"https://reqres.in/img/faces/5-image.jpg",
       "email":"charles.morris@reqres.in",
       "first_name":"Charles",
       "id":15,
       "last_name":"Morris"
    },
    {
       "avatar":"https://reqres.in/img/faces/6-image.jpg",
       "email":"tracey.ramos@reqres.in",
       "first_name":"Tracey",
       "id":16,
       "last_name":"Ramos"
    }
 ];

 export const singleUSer ={
   "avatar":"https://reqres.in/img/faces/7-image.jpg",
   "email":"traceydw.ramos@reqres.in",
   "first_name":"singh",
   "id":7,
   "last_name":"Ramos"
};